import '../../../styles/marketing.css';
import { Header } from '@/components/marketing/Header';
import { Footer } from '@/components/marketing/Footer';

export const metadata = {
  title: 'Terms of Service — HireDax',
};

export default function TermsPage() {
  return (
    <div className="mkt-page">
      <Header />

      <main className="mkt-legal-main">
        <div className="mkt-legal-card">

          <h1 className="mkt-legal-title">Terms of Service</h1>
          <p className="mkt-legal-date">Effective Date: June 09, 2026</p>

          <p className="mkt-legal-p">
            By accessing or using HireDax, you agree to be bound by these Terms of Service.
            Please read them carefully before using the platform.
          </p>

          <h2 className="mkt-legal-section">Acceptance of Terms</h2>
          <p className="mkt-legal-p">
            By creating an account or using any part of the HireDax service, you agree to these
            Terms of Service and our Privacy Policy. If you do not agree to these terms, do not
            use the service.
          </p>

          <h2 className="mkt-legal-section">Description of Service</h2>
          <p className="mkt-legal-p">
            HireDax is an AI-powered inbound voice and visual estimating agent for home service
            businesses. The service enables operators to receive AI-generated job estimates from
            customer-uploaded photos during live phone calls, subject to mandatory operator
            approval before any price is communicated to the customer.
          </p>

          <h2 className="mkt-legal-section">Operator Responsibilities</h2>
          <p className="mkt-legal-p">
            As a HireDax operator, you are responsible for: maintaining accurate business
            information in your account; reviewing and approving all AI-generated estimates
            before they are communicated to customers; ensuring your use of the service complies
            with all applicable laws; and maintaining the confidentiality of your login
            credentials.
          </p>

          <h2 className="mkt-legal-section">AI-Generated Estimates</h2>
          <p className="mkt-legal-p">
            All estimates generated by HireDax are preliminary and subject to operator review
            and approval. HireDax estimates are clearly labeled as &ldquo;Preliminary Visual
            Estimate Only&rdquo; and final pricing is confirmed after on-site inspection.
            HireDax is not responsible for discrepancies between AI-generated estimates and
            final job costs.
          </p>

          <h2 className="mkt-legal-section">SMS Terms and Conditions</h2>
          <p className="mkt-legal-p">
            These terms apply to SMS messages sent to and from AmazingDotAI, LLC DBA HireDax.
          </p>
          <p className="mkt-legal-p">
            HireDax sends the following types of SMS messages: secure photo upload links (Sight
            Links) sent to customers during active estimate calls; booking confirmation messages;
            and service-related notifications.
          </p>
          <p className="mkt-legal-p">
            You can cancel the SMS service at any time. Just text &ldquo;STOP&rdquo;. After you
            send the SMS message &ldquo;STOP&rdquo; to us, we will send you an SMS message to
            confirm that you have been unsubscribed. After this, you will no longer receive SMS
            messages from us. If you want to join again, send the SMS message &ldquo;START&rdquo;
            and we will start sending SMS messages to you again.
          </p>
          <p className="mkt-legal-p">
            If you are experiencing issues with the messaging program you can reply with the
            keyword HELP for more assistance, or you can get help directly at{' '}
            <a href="mailto:team@amazing.ai" className="mkt-legal-link">team@amazing.ai</a>.
          </p>
          <p className="mkt-legal-p">
            Carriers are not liable for delayed or undelivered messages.
          </p>
          <p className="mkt-legal-p">
            Message and data rates may apply for any messages sent to you from us and to us from
            you. Message frequency varies. If you have any questions about your text plan or data
            plan, it is best to contact your wireless provider.
          </p>
          <p className="mkt-legal-p">
            If you have any questions regarding privacy, please read our privacy policy:{' '}
            <a href="https://www.hiredax.com/privacy" className="mkt-legal-link">
              https://www.hiredax.com/privacy
            </a>
          </p>

          <h2 className="mkt-legal-section">Limitation of Liability</h2>
          <p className="mkt-legal-p">
            HireDax and AmazingDotAi, LLC are not liable for any indirect, incidental, special,
            or consequential damages arising from your use of the service. Our total liability
            for any claim arising from these terms shall not exceed the amount you paid for the
            service in the three months preceding the claim.
          </p>

          <h2 className="mkt-legal-section">Modifications to Terms</h2>
          <p className="mkt-legal-p">
            We reserve the right to modify these Terms of Service at any time. We will provide
            notice of significant changes by posting a prominent notice on our website. Continued
            use of the service after changes constitutes acceptance of the updated terms.
          </p>

          <h2 className="mkt-legal-section">Governing Law</h2>
          <p className="mkt-legal-p">
            These Terms of Service are governed by the laws of the State of Georgia, United
            States, without regard to its conflict of law provisions.
          </p>

          <h2 className="mkt-legal-section">Contact Us</h2>
          <p className="mkt-legal-p">
            AmazingDotAi, LLC DBA HireDax<br />
            Email:{' '}
            <a href="mailto:team@amazing.ai" className="mkt-legal-link">team@amazing.ai</a><br />
            Website:{' '}
            <a href="https://www.hiredax.com" className="mkt-legal-link">https://www.hiredax.com</a>
          </p>

        </div>
      </main>

      <Footer />
    </div>
  );
}
